#include <iostream>
#include <chrono>
#include <mutex>
#include <fstream>
#include <filesystem>
#include <unordered_map>
#include "../src/hashtable/Hashtable.h"

using namespace std;

int main(int argc, char **argv) {
    // A hash table with 8 byte keys and values
    const std::string data_location = "/mnt/pmem0/vogel/tabletest";
    uint64_t key = 512;
    uint64_t key_nolog = 513;

    // Let's start with fixed size records
    {
        // Disclaimer: Please always use hash partitioning over range partitioning unless you EXACTLY know what you are doing! ;)
        Hashtable<uint64_t, uint64_t, PartitionType::Hash> fixed_size_ht(data_location, true);

        fixed_size_ht.insert(key, 1024);

        uint64_t value;
        std::cout << "Found inserted key? " << fixed_size_ht.lookup(key, reinterpret_cast<uint8_t *>(&value)) << ", ";
        std::cout << "Value is: " << value << std::endl;

        fixed_size_ht.remove(key);
        std::cout << "Found deleted key? " << fixed_size_ht.lookup(key, reinterpret_cast<uint8_t *>(&value))
                  << std::endl;

        // Let's reinsert the key
        fixed_size_ht.insert(key, 1024);

        // An update is just another insert
        fixed_size_ht.insert(key, 1337);

        // Let's insert another key without logging
        //TODO: This interface is stupid - you shouldn't have to specify it's not a tombstone to skip logging
        fixed_size_ht.insert(key_nolog, 1025, false, false);
        std::cout << "Found inserted key without logging? "
                  << fixed_size_ht.lookup(key_nolog, reinterpret_cast<uint8_t *>(&value)) << ", ";
        std::cout << "Value is: " << value << std::endl;

        // As Plush is append only, count includes tombstone records and updates that haven't been merged yet.
        fixed_size_ht.count();
    }
    // Let's kill the hash table by letting it go out of scope

    {
        // Now, let's recover it
        Hashtable<uint64_t, uint64_t, PartitionType::Hash> fixed_size_ht(data_location, false);

        uint64_t value;
        std::cout << "Logged key survived recovery? " << fixed_size_ht.lookup(key, reinterpret_cast<uint8_t *>(&value))
                  << ", ";
        std::cout << "Value is: " << value << std::endl;

        std::cout << "Not logged key survived recovery? "
                  << fixed_size_ht.lookup(key_nolog, reinterpret_cast<uint8_t *>(&value)) << std::endl;

        // Now let's reinsert the key without log but this time create a checkpoint.
        fixed_size_ht.insert(key_nolog, 1026, false, false);

        // Usually, you would create a checkpoint after having bulk loaded millions of records.
        fixed_size_ht.checkpoint(32); //TODO: Thread count currently needs to be a power of 2.

    }

    {
        // Let's recover again
        Hashtable<uint64_t, uint64_t, PartitionType::Hash> fixed_size_ht(data_location, false);

        uint64_t value;
        std::cout << "Not initially logged, but checkpointed key survived recovery? "
                  << fixed_size_ht.lookup(key_nolog, reinterpret_cast<uint8_t *>(&value)) << ", ";
        std::cout << "Value is: " << value << std::endl;

    }

    {
        // Plush with variable sized records works exactly the same.
        // Note that initializiation here takes really long as Plush has to prepare all the (really big) payload logs
        Hashtable<std::span<const std::byte>, std::span<const std::byte>, PartitionType::Hash> table("/mnt/pmem0/vogel/tabletest", true);

        std::string key = "Das Lied von der Glocke";
        std::string value = "Vivos voco\n"
                            "\n"
                            "Mortuos plango\n"
                            "\n"
                            "Fulgura frango\n"
                            "\n"
                            "Fest gemauert in der Erden\n"
                            "\n"
                            "Steht die Form, aus Lehm gebrannt.\n"
                            "\n"
                            "Heute muß die Glocke werden,\n"
                            "\n"
                            "Frisch, Gesellen, seid zur Hand.\n"
                            "\n"
                            "Von der Stirne heiß\n"
                            "\n"
                            "Rinnen muß der Schweiß,\n"
                            "\n"
                            "Soll das Werk den Meister loben,\n"
                            "\n"
                            "Doch der Segen kommt von oben.[429]\n"
                            "\n"
                            "Zum Werke, das wir ernst bereiten,\n"
                            "\n"
                            "Geziemt sich wohl ein ernstes Wort;\n"
                            "\n"
                            "Wenn gute Reden sie begleiten,\n"
                            "\n"
                            "Dann fließt die Arbeit munter fort.\n"
                            "\n"
                            "So laßt uns jetzt mit Fleiß betrachten,\n"
                            "\n"
                            "Was durch die schwache Kraft entspringt,\n"
                            "\n"
                            "Den schlechten Mann muß man verachten,\n"
                            "\n"
                            "Der nie bedacht, was er vollbringt.\n"
                            "\n"
                            "Das ists ja, was den Menschen zieret,\n"
                            "\n"
                            "Und dazu ward ihm der Verstand,\n"
                            "\n"
                            "Daß er im innern Herzen spüret,\n"
                            "\n"
                            "Was er erschafft mit seiner Hand.\n"
                            "\n"
                            "Nehmet Holz vom Fichtenstamme,\n"
                            "\n"
                            "Doch recht trocken laßt es sein,\n"
                            "\n"
                            "Daß die eingepreßte Flamme\n"
                            "\n"
                            "Schlage zu dem Schwalch hinein.\n"
                            "\n"
                            "Kocht des Kupfers Brei,\n"
                            "\n"
                            "Schnell das Zinn herbei,\n"
                            "\n"
                            "Daß die zähe Glockenspeise\n"
                            "\n"
                            "Fließe nach der rechten Weise.\n"
                            "\n"
                            "Was in des Dammes tiefer Grube\n"
                            "\n"
                            "Die Hand mit Feuers Hülfe baut,\n"
                            "\n"
                            "Hoch auf des Turmes Glockenstube\n"
                            "\n"
                            "Da wird es von uns zeugen laut.\n"
                            "\n"
                            "Noch dauern wirds in späten Tagen\n"
                            "\n"
                            "Und rühren vieler Menschen Ohr\n"
                            "\n"
                            "Und wird mit dem Betrübten klagen\n"
                            "\n"
                            "Und stimmen zu der Andacht Chor.\n"
                            "\n"
                            "Was unten tief dem Erdensohne\n"
                            "\n"
                            "Das wechselnde Verhängnis bringt,\n"
                            "\n"
                            "Das schlägt an die metallne Krone,\n"
                            "\n"
                            "Die es erbaulich weiterklingt.[430]\n"
                            "\n"
                            "Weiße Blasen seh ich springen,\n"
                            "\n"
                            "Wohl! die Massen sind im Fluß.\n"
                            "\n"
                            "Laßts mit Aschensalz durchdringen,\n"
                            "\n"
                            "Das befördert schnell den Guß.\n"
                            "\n"
                            "Auch von Schaume rein\n"
                            "\n"
                            "Muß die Mischung sein,\n"
                            "\n"
                            "Daß vom reinlichen Metalle\n"
                            "\n"
                            "Rein und voll die Stimme schalle.\n"
                            "\n"
                            "Denn mit der Freude Feierklange\n"
                            "\n"
                            "Begrüßt sie das geliebte Kind\n"
                            "\n"
                            "Auf seines Lebens erstem Gange,\n"
                            "\n"
                            "Den es in Schlafes Arm beginnt;\n"
                            "\n"
                            "Ihm ruhen noch im Zeitenschoße\n"
                            "\n"
                            "Die schwarzen und die heitern Lose,\n"
                            "\n"
                            "Der Mutterliebe zarte Sorgen\n"
                            "\n"
                            "Bewachen seinen goldnen Morgen. –\n"
                            "\n"
                            "Die Jahre fliehen pfeilgeschwind.\n"
                            "\n"
                            "Vom Mädchen reißt sich stolz der Knabe,\n"
                            "\n"
                            "Er stürmt ins Leben wild hinaus,\n"
                            "\n"
                            "Durchmißt die Welt am Wanderstabe.\n"
                            "\n"
                            "Fremd kehrt er heim ins Vaterhaus,\n"
                            "\n"
                            "Und herrlich, in der Jugend Prangen,\n"
                            "\n"
                            "Wie ein Gebild aus Himmelshöhn,\n"
                            "\n"
                            "Mit züchtigen, verschämten Wangen\n"
                            "\n"
                            "Sieht er die Jungfrau vor sich stehn.\n"
                            "\n"
                            "Da faßt ein namenloses Sehnen\n"
                            "\n"
                            "Des Jünglings Herz, er irrt allein,\n"
                            "\n"
                            "Aus seinen Augen brechen Tränen,\n"
                            "\n"
                            "Er flieht der Brüder wilden Reihn.\n"
                            "\n"
                            "Errötend folgt er ihren Spuren\n"
                            "\n"
                            "Und ist von ihrem Gruß beglückt,\n"
                            "\n"
                            "Das Schönste sucht er auf den Fluren,\n"
                            "\n"
                            "Womit er seine Liebe schmückt.\n"
                            "\n"
                            "O! zarte Sehnsucht, süßes Hoffen,\n"
                            "\n"
                            "Der ersten Liebe goldne Zeit,[431]\n"
                            "\n"
                            "Das Auge sieht den Himmel offen,\n"
                            "\n"
                            "Es schwelgt das Herz in Seligkeit.\n"
                            "\n"
                            "O! daß sie ewig grünen bliebe,\n"
                            "\n"
                            "Die schöne Zeit der jungen Liebe!\n"
                            "\n"
                            "Wie sich schon die Pfeifen bräunen!\n"
                            "\n"
                            "Dieses Stäbchen tauch ich ein,\n"
                            "\n"
                            "Sehn wirs überglast erscheinen,\n"
                            "\n"
                            "Wirds zum Gusse zeitig sein.\n"
                            "\n"
                            "Jetzt, Gesellen, frisch!\n"
                            "\n"
                            "Prüft mir das Gemisch,\n"
                            "\n"
                            "Ob das Spröde mit dem Weichen\n"
                            "\n"
                            "Sich vereint zum guten Zeichen.\n"
                            "\n"
                            "Denn wo das Strenge mit dem Zarten,\n"
                            "\n"
                            "Wo Starkes sich und Mildes paarten,\n"
                            "\n"
                            "Da gibt es einen guten Klang.\n"
                            "\n"
                            "Drum prüfe, wer sich ewig bindet,\n"
                            "\n"
                            "Ob sich das Herz zum Herzen findet!\n"
                            "\n"
                            "Der Wahn ist kurz, die Reu ist lang.\n"
                            "\n"
                            "Lieblich in der Bräute Locken\n"
                            "\n"
                            "Spielt der jungfräuliche Kranz,\n"
                            "\n"
                            "Wenn die hellen Kirchenglocken\n"
                            "\n"
                            "Laden zu des Festes Glanz.\n"
                            "\n"
                            "Ach! des Lebens schönste Feier\n"
                            "\n"
                            "Endigt auch den Lebensmai,\n"
                            "\n"
                            "Mit dem Gürtel, mit dem Schleier\n"
                            "\n"
                            "Reißt der schöne Wahn entzwei.\n"
                            "\n"
                            "Die Leidenschaft flieht!\n"
                            "\n"
                            "Die Liebe muß bleiben,\n"
                            "\n"
                            "Die Blume verblüht,\n"
                            "\n"
                            "Die Frucht muß treiben.\n"
                            "\n"
                            "Der Mann muß hinaus\n"
                            "\n"
                            "Ins feindliche Leben,\n"
                            "\n"
                            "Muß wirken und streben\n"
                            "\n"
                            "Und pflanzen und schaffen,[432]\n"
                            "\n"
                            "Erlisten, erraffen,\n"
                            "\n"
                            "Muß wetten und wagen,\n"
                            "\n"
                            "Das Glück zu erjagen.\n"
                            "\n"
                            "Da strömet herbei die unendliche Gabe,\n"
                            "\n"
                            "Es füllt sich der Speicher mit köstlicher Habe,\n"
                            "\n"
                            "Die Räume wachsen, es dehnt sich das Haus.\n"
                            "\n"
                            "Und drinnen waltet\n"
                            "\n"
                            "Die züchtige Hausfrau,\n"
                            "\n"
                            "Die Mutter der Kinder,\n"
                            "\n"
                            "Und herrschet weise\n"
                            "\n"
                            "Im häuslichen Kreise,\n"
                            "\n"
                            "Und lehret die Mädchen\n"
                            "\n"
                            "Und wehret den Knaben,\n"
                            "\n"
                            "Und reget ohn Ende\n"
                            "\n"
                            "Die fleißigen Hände,\n"
                            "\n"
                            "Und mehrt den Gewinn\n"
                            "\n"
                            "Mit ordnendem Sinn.\n"
                            "\n"
                            "Und füllet mit Schätzen die duftenden Laden,\n"
                            "\n"
                            "Und dreht um die schnurrende Spindel den Faden,\n"
                            "\n"
                            "Und sammelt im reinlich geglätteten Schrein\n"
                            "\n"
                            "Die schimmernde Wolle, den schneeigten Lein,\n"
                            "\n"
                            "Und füget zum Guten den Glanz und den Schimmer,\n"
                            "\n"
                            "Und ruhet nimmer.\n"
                            "\n"
                            "Und der Vater mit frohem Blick\n"
                            "\n"
                            "Von des Hauses weitschauendem Giebel\n"
                            "\n"
                            "Überzählet sein blühend Glück,\n"
                            "\n"
                            "Siehet der Pfosten ragende Bäume\n"
                            "\n"
                            "Und der Scheunen gefüllte Räume\n"
                            "\n"
                            "Und die Speicher, vom Segen gebogen,\n"
                            "\n"
                            "Und des Kornes bewegte Wogen,\n"
                            "\n"
                            "Rühmt sich mit stolzem Mund:\n"
                            "\n"
                            "Fest, wie der Erde Grund,\n"
                            "\n"
                            "Gegen des Unglücks Macht\n"
                            "\n"
                            "Steht mir des Hauses Pracht!\n"
                            "\n"
                            "Doch mit des Geschickes Mächten[433]\n"
                            "\n"
                            "Ist kein ewger Bund zu flechten,\n"
                            "\n"
                            "Und das Unglück schreitet schnell.\n"
                            "\n"
                            "Wohl! Nun kann der Guß beginnen,\n"
                            "\n"
                            "Schön gezacket ist der Bruch.\n"
                            "\n"
                            "Doch, bevor wirs lassen rinnen,\n"
                            "\n"
                            "Betet einen frommen Spruch!\n"
                            "\n"
                            "Stoßt den Zapfen aus!\n"
                            "\n"
                            "Gott bewahr das Haus.\n"
                            "\n"
                            "Rauchend in des Henkels Bogen\n"
                            "\n"
                            "Schießts mit feuerbraunen Wogen.\n"
                            "\n"
                            "Wohltätig ist des Feuers Macht,\n"
                            "\n"
                            "Wenn sie der Mensch bezähmt, bewacht,\n"
                            "\n"
                            "Und was er bildet, was er schafft,\n"
                            "\n"
                            "Das dankt er dieser Himmelskraft,\n"
                            "\n"
                            "Doch furchtbar wird die Himmelskraft,\n"
                            "\n"
                            "Wenn sie der Fessel sich entrafft,\n"
                            "\n"
                            "Einhertritt auf der eignen Spur\n"
                            "\n"
                            "Die freie Tochter der Natur.\n"
                            "\n"
                            "Wehe, wenn sie losgelassen\n"
                            "\n"
                            "Wachsend ohne Widerstand\n"
                            "\n"
                            "Durch die volkbelebten Gassen\n"
                            "\n"
                            "Wälzt den ungeheuren Brand!\n"
                            "\n"
                            "Denn die Elemente hassen\n"
                            "\n"
                            "Das Gebild der Menschenhand.\n"
                            "\n"
                            "Aus der Wolke\n"
                            "\n"
                            "Quillt der Segen,\n"
                            "\n"
                            "Strömt der Regen,\n"
                            "\n"
                            "Aus der Wolke, ohne Wahl,\n"
                            "\n"
                            "Zuckt der Strahl!\n"
                            "\n"
                            "Hört ihrs wimmern hoch vom Turm?\n"
                            "\n"
                            "Das ist Sturm!\n"
                            "\n"
                            "Rot wie Blut\n"
                            "\n"
                            "Ist der Himmel,\n"
                            "\n"
                            "Das ist nicht des Tages Glut!\n"
                            "\n"
                            "Welch Getümmel[434]\n"
                            "\n"
                            "Straßen auf!\n"
                            "\n"
                            "Dampf wallt auf!\n"
                            "\n"
                            "Flackernd steigt die Feuersäule,\n"
                            "\n"
                            "Durch der Straße lange Zeile\n"
                            "\n"
                            "Wächst es fort mit Windeseile,\n"
                            "\n"
                            "Kochend wie aus Ofens Rachen\n"
                            "\n"
                            "Glühn die Lüfte, Balken krachen,\n"
                            "\n"
                            "Pfosten stürzen, Fenster klirren,\n"
                            "\n"
                            "Kinder jammern, Mütter irren,\n"
                            "\n"
                            "Tiere wimmern\n"
                            "\n"
                            "Unter Trümmern,\n"
                            "\n"
                            "Alles rennet, rettet, flüchtet,\n"
                            "\n"
                            "Taghell ist die Nacht gelichtet,\n"
                            "\n"
                            "Durch der Hände lange Kette\n"
                            "\n"
                            "Um die Wette\n"
                            "\n"
                            "Fliegt der Eimer, hoch im Bogen\n"
                            "\n"
                            "Sprützen Quellen, Wasserwogen.\n"
                            "\n"
                            "Heulend kommt der Sturm geflogen,\n"
                            "\n"
                            "Der die Flamme brausend sucht.\n"
                            "\n"
                            "Prasselnd in die dürre Frucht\n"
                            "\n"
                            "Fällt sie, in des Speichers Räume,\n"
                            "\n"
                            "In der Sparren dürre Bäume,\n"
                            "\n"
                            "Und als wollte sie im Wehen\n"
                            "\n"
                            "Mit sich fort der Erde Wucht\n"
                            "\n"
                            "Reißen, in gewaltger Flucht,\n"
                            "\n"
                            "Wächst sie in des Himmels Höhen\n"
                            "\n"
                            "Rießengroß!\n"
                            "\n"
                            "Hoffnungslos\n"
                            "\n"
                            "Weicht der Mensch der Götterstärke,\n"
                            "\n"
                            "Müßig sieht er seine Werke\n"
                            "\n"
                            "Und bewundernd untergehen.\n"
                            "\n"
                            "Leergebrannt\n"
                            "\n"
                            "Ist die Stätte,\n"
                            "\n"
                            "Wilder Stürme rauhes Bette,\n"
                            "\n"
                            "In den öden Fensterhöhlen[435]\n"
                            "\n"
                            "Wohnt das Grauen,\n"
                            "\n"
                            "Und des Himmels Wolken schauen\n"
                            "\n"
                            "Hoch hinein.\n"
                            "\n"
                            "Einen Blick\n"
                            "\n"
                            "Nach dem Grabe\n"
                            "\n"
                            "Seiner Habe\n"
                            "\n"
                            "Sendet noch der Mensch zurück –\n"
                            "\n"
                            "Greift fröhlich dann zum Wanderstabe,\n"
                            "\n"
                            "Was Feuers Wut ihm auch geraubt,\n"
                            "\n"
                            "Ein süßer Trost ist ihm geblieben,\n"
                            "\n"
                            "Er zählt die Häupter seiner Lieben,\n"
                            "\n"
                            "Und sieh! ihm fehlt kein teures Haupt.\n"
                            "\n"
                            "In die Erd ists aufgenommen,\n"
                            "\n"
                            "Glücklich ist die Form gefüllt,\n"
                            "\n"
                            "Wirds auch schön zutage kommen,\n"
                            "\n"
                            "Daß es Fleiß und Kunst vergilt?\n"
                            "\n"
                            "Wenn der Guß mißlang?\n"
                            "\n"
                            "Wenn die Form zersprang?\n"
                            "\n"
                            "Ach! vielleicht, indem wir hoffen,\n"
                            "\n"
                            "Hat uns Unheil schon getroffen.\n"
                            "\n"
                            "Dem dunkeln Schoß der heilgen Erde\n"
                            "\n"
                            "Vertrauen wir der Hände Tat,\n"
                            "\n"
                            "Vertraut der Sämann seine Saat\n"
                            "\n"
                            "Und hofft, daß sie entkeimen werde\n"
                            "\n"
                            "Zum Segen, nach des Himmels Rat.\n"
                            "\n"
                            "Noch köstlicheren Samen bergen\n"
                            "\n"
                            "Wir traurend in der Erde Schoß\n"
                            "\n"
                            "Und hoffen, daß er aus den Särgen\n"
                            "\n"
                            "Erblühen soll zu schönerm Los.\n"
                            "\n"
                            "Von dem Dome,\n"
                            "\n"
                            "Schwer und bang,\n"
                            "\n"
                            "Tönt die Glocke\n"
                            "\n"
                            "Grabgesang.[436]\n"
                            "\n"
                            "Ernst begleiten ihre Trauerschläge\n"
                            "\n"
                            "Einen Wandrer auf dem letzten Wege.\n"
                            "\n"
                            "Ach! die Gattin ists, die teure,\n"
                            "\n"
                            "Ach! es ist die treue Mutter,\n"
                            "\n"
                            "Die der schwarze Fürst der Schatten\n"
                            "\n"
                            "Wegführt aus dem Arm des Gatten,\n"
                            "\n"
                            "Aus der zarten Kinder Schar,\n"
                            "\n"
                            "Die sie blühend ihm gebar,\n"
                            "\n"
                            "Die sie an der treuen Brust\n"
                            "\n"
                            "Wachsen sah mit Mutterlust –\n"
                            "\n"
                            "Ach! des Hauses zarte Bande\n"
                            "\n"
                            "Sind gelöst auf immerdar,\n"
                            "\n"
                            "Denn sie wohnt im Schattenlande,\n"
                            "\n"
                            "Die des Hauses Mutter war,\n"
                            "\n"
                            "Denn es fehlt ihr treues Walten,\n"
                            "\n"
                            "Ihre Sorge wacht nicht mehr,\n"
                            "\n"
                            "An verwaister Stätte schalten\n"
                            "\n"
                            "Wird die Fremde, liebeleer.\n"
                            "\n"
                            "Bis die Glocke sich verkühlet,\n"
                            "\n"
                            "Laßt die strenge Arbeit ruhn,\n"
                            "\n"
                            "Wie im Laub der Vogel spielet,\n"
                            "\n"
                            "Mag sich jeder gütlich tun.\n"
                            "\n"
                            "Winkt der Sterne Licht,\n"
                            "\n"
                            "Ledig aller Pflicht\n"
                            "\n"
                            "Hört der Pursch die Vesper schlagen,\n"
                            "\n"
                            "Meister muß sich immer plagen.\n"
                            "\n"
                            "Munter fördert seine Schritte\n"
                            "\n"
                            "Fern im wilden Forst der Wandrer\n"
                            "\n"
                            "Nach der lieben Heimathütte.\n"
                            "\n"
                            "Blökend ziehen\n"
                            "\n"
                            "Heim die Schafe,\n"
                            "\n"
                            "Und der Rinder\n"
                            "\n"
                            "Breitgestirnte, glatte Scharen\n"
                            "\n"
                            "Kommen brüllend,\n"
                            "\n"
                            "Die gewohnten Ställe füllend.[437]\n"
                            "\n"
                            "Schwer herein\n"
                            "\n"
                            "Schwankt der Wagen,\n"
                            "\n"
                            "Kornbeladen,\n"
                            "\n"
                            "Bunt von Farben\n"
                            "\n"
                            "Auf den Garben\n"
                            "\n"
                            "Liegt der Kranz,\n"
                            "\n"
                            "Und das junge Volk der Schnitter\n"
                            "\n"
                            "Fliegt zum Tanz.\n"
                            "\n"
                            "Markt und Straße werden stiller,\n"
                            "\n"
                            "Um des Lichts gesellge Flamme\n"
                            "\n"
                            "Sammeln sich die Hausbewohner,\n"
                            "\n"
                            "Und das Stadttor schließt sich knarrend.\n"
                            "\n"
                            "Schwarz bedecket\n"
                            "\n"
                            "Sich die Erde,\n"
                            "\n"
                            "Doch den sichern Bürger schrecket\n"
                            "\n"
                            "Nicht die Nacht,\n"
                            "\n"
                            "Die den Bösen gräßlich wecket,\n"
                            "\n"
                            "Denn das Auge des Gesetzes wacht.\n"
                            "\n"
                            "Heilge Ordnung, segenreiche\n"
                            "\n"
                            "Himmelstochter, die das Gleiche\n"
                            "\n"
                            "Frei und leicht und freudig bindet,\n"
                            "\n"
                            "Die der Städte Bau gegründet,\n"
                            "\n"
                            "Die herein von den Gefilden\n"
                            "\n"
                            "Rief den ungesellgen Wilden,\n"
                            "\n"
                            "Eintrat in der Menschen Hütten,\n"
                            "\n"
                            "Sie gewöhnt zu sanften Sitten\n"
                            "\n"
                            "Und das teuerste der Bande\n"
                            "\n"
                            "Wob, den Trieb zum Vaterlande!\n"
                            "\n"
                            "Tausend fleißge Hände regen,\n"
                            "\n"
                            "Helfen sich in munterm Bund,\n"
                            "\n"
                            "Und in feurigem Bewegen\n"
                            "\n"
                            "Werden alle Kräfte kund.\n"
                            "\n"
                            "Meister rührt sich und Geselle\n"
                            "\n"
                            "In der Freiheit heilgem Schutz.[438]\n"
                            "\n"
                            "Jeder freut sich seiner Stelle,\n"
                            "\n"
                            "Bietet dem Verächter Trutz.\n"
                            "\n"
                            "Arbeit ist des Bürgers Zierde,\n"
                            "\n"
                            "Segen ist der Mühe Preis,\n"
                            "\n"
                            "Ehrt den König seine Würde,\n"
                            "\n"
                            "Ehret uns der Hände Fleiß.\n"
                            "\n"
                            "Holder Friede,\n"
                            "\n"
                            "Süße Eintracht,\n"
                            "\n"
                            "Weilet, weilet\n"
                            "\n"
                            "Freundlich über dieser Stadt!\n"
                            "\n"
                            "Möge nie der Tag erscheinen,\n"
                            "\n"
                            "Wo des rauhen Krieges Horden\n"
                            "\n"
                            "Dieses stille Tal durchtoben,\n"
                            "\n"
                            "Wo der Himmel,\n"
                            "\n"
                            "Den des Abends sanfte Röte\n"
                            "\n"
                            "Lieblich malt,\n"
                            "\n"
                            "Von der Dörfer, von der Städte\n"
                            "\n"
                            "Wildem Brande schrecklich strahlt!\n"
                            "\n"
                            "Nun zerbrecht mir das Gebäude,\n"
                            "\n"
                            "Seine Absicht hats erfüllt,\n"
                            "\n"
                            "Daß sich Herz und Auge weide\n"
                            "\n"
                            "An dem wohlgelungnen Bild.\n"
                            "\n"
                            "Schwingt den Hammer, schwingt,\n"
                            "\n"
                            "Bis der Mantel springt,\n"
                            "\n"
                            "Wenn die Glock soll auferstehen,\n"
                            "\n"
                            "Muß die Form in Stücken gehen.\n"
                            "\n"
                            "Der Meister kann die Form zerbrechen\n"
                            "\n"
                            "Mit weiser Hand, zur rechten Zeit,\n"
                            "\n"
                            "Doch wehe, wenn in Flammenbächen\n"
                            "\n"
                            "Das glühnde Erz sich selbst befreit!\n"
                            "\n"
                            "Blindwütend mit des Donners Krachen\n"
                            "\n"
                            "Zersprengt es das geborstne Haus,\n"
                            "\n"
                            "Und wie aus offnem Höllenrachen\n"
                            "\n"
                            "Speit es Verderben zündend aus;\n"
                            "\n"
                            "Wo rohe Kräfte sinnlos walten,[439]\n"
                            "\n"
                            "Da kann sich kein Gebild gestalten,\n"
                            "\n"
                            "Wenn sich die Völker selbst befrein,\n"
                            "\n"
                            "Da kann die Wohlfahrt nicht gedeihn.\n"
                            "\n"
                            "Weh, wenn sich in dem Schoß der Städte\n"
                            "\n"
                            "Der Feuerzunder still gehäuft,\n"
                            "\n"
                            "Das Volk, zerreißend seine Kette,\n"
                            "\n"
                            "Zur Eigenhilfe schrecklich greift!\n"
                            "\n"
                            "Da zerret an der Glocke Strängen\n"
                            "\n"
                            "Der Aufruhr, daß sie heulend schallt\n"
                            "\n"
                            "Und, nur geweiht zu Friedensklängen,\n"
                            "\n"
                            "Die Losung anstimmt zur Gewalt.\n"
                            "\n"
                            "Freiheit und Gleichheit! hört man schallen,\n"
                            "\n"
                            "Der ruhge Bürger greift zur Wehr,\n"
                            "\n"
                            "Die Straßen füllen sich, die Hallen,\n"
                            "\n"
                            "Und Würgerbanden ziehn umher,\n"
                            "\n"
                            "Da werden Weiber zu Hyänen\n"
                            "\n"
                            "Und treiben mit Entsetzen Scherz,\n"
                            "\n"
                            "Noch zuckend, mit des Panthers Zähnen,\n"
                            "\n"
                            "Zerreißen sie des Feindes Herz.\n"
                            "\n"
                            "Nichts Heiliges ist mehr, es lösen\n"
                            "\n"
                            "Sich alle Bande frommer Scheu,\n"
                            "\n"
                            "Der Gute räumt den Platz dem Bösen,\n"
                            "\n"
                            "Und alle Laster walten frei.\n"
                            "\n"
                            "Gefährlich ists, den Leu zu wecken,\n"
                            "\n"
                            "Verderblich ist des Tigers Zahn,\n"
                            "\n"
                            "Jedoch der schrecklichste der Schrecken,\n"
                            "\n"
                            "Das ist der Mensch in seinem Wahn.\n"
                            "\n"
                            "Weh denen, die dem Ewigblinden\n"
                            "\n"
                            "Des Lichtes Himmelsfackel leihn!\n"
                            "\n"
                            "Sie strahlt ihm nicht, sie kann nur zünden\n"
                            "\n"
                            "Und äschert Städt und Länder ein.\n"
                            "\n"
                            "Freude hat mir Gott gegeben!\n"
                            "\n"
                            "Sehet! wie ein goldner Stern[440]\n"
                            "\n"
                            "Aus der Hülse, blank und eben,\n"
                            "\n"
                            "Schält sich der metallne Kern.\n"
                            "\n"
                            "Von dem Helm zum Kranz\n"
                            "\n"
                            "Spielts wie Sonnenglanz,\n"
                            "\n"
                            "Auch des Wappens nette Schilder\n"
                            "\n"
                            "Loben den erfahrnen Bilder.\n"
                            "\n"
                            "Herein! herein!\n"
                            "\n"
                            "Gesellen alle, schließt den Reihen,\n"
                            "\n"
                            "Daß wir die Glocke taufend weihen,\n"
                            "\n"
                            "Concordia soll ihr Name sein,\n"
                            "\n"
                            "Zur Eintracht, zu herzinnigem Vereine\n"
                            "\n"
                            "Versammle sie die liebende Gemeine.\n"
                            "\n"
                            "Und dies sei fortan ihr Beruf,\n"
                            "\n"
                            "Wozu der Meister sie erschuf!\n"
                            "\n"
                            "Hoch überm niedern Erdenleben\n"
                            "\n"
                            "Soll sie in blauem Himmelszelt\n"
                            "\n"
                            "Die Nachbarin des Donners schweben\n"
                            "\n"
                            "Und grenzen an die Sternenwelt,\n"
                            "\n"
                            "Soll eine Stimme sein von oben,\n"
                            "\n"
                            "Wie der Gestirne helle Schar,\n"
                            "\n"
                            "Die ihren Schöpfer wandelnd loben\n"
                            "\n"
                            "Und führen das bekränzte Jahr.\n"
                            "\n"
                            "Nur ewigen und ernsten Dingen\n"
                            "\n"
                            "Sei ihr metallner Mund geweiht,\n"
                            "\n"
                            "Und stündlich mit den schnellen Schwingen\n"
                            "\n"
                            "Berühr im Fluge sie die Zeit,\n"
                            "\n"
                            "Dem Schicksal leihe sie die Zunge,\n"
                            "\n"
                            "Selbst herzlos, ohne Mitgefühl,\n"
                            "\n"
                            "Begleite sie mit ihrem Schwunge\n"
                            "\n"
                            "Des Lebens wechselvolles Spiel.\n"
                            "\n"
                            "Und wie der Klang im Ohr vergehet,\n"
                            "\n"
                            "Der mächtig tönend ihr entschallt,\n"
                            "\n"
                            "So lehre sie, daß nichts bestehet,\n"
                            "\n"
                            "Das alles Irdische verhallt.[441]\n"
                            "\n"
                            "Jetzo mit der Kraft des Stranges\n"
                            "\n"
                            "Wiegt die Glock mir aus der Gruft,\n"
                            "\n"
                            "Daß sie in das Reich des Klanges\n"
                            "\n"
                            "Steige, in die Himmelsluft.\n"
                            "\n"
                            "Ziehet, ziehet, hebt!\n"
                            "\n"
                            "Sie bewegt sich, schwebt,\n"
                            "\n"
                            "Freude dieser Stadt bedeute,\n"
                            "\n"
                            "Friede sei ihr erst Geläute.";


        table.insert(std::span<std::byte>(reinterpret_cast<std::byte*>(key.data()), key.size()),
                     std::span<std::byte>(reinterpret_cast<std::byte*>(value.data()), value.size()));

        std::unique_ptr<uint8_t[]> search_result = std::make_unique<uint8_t[]>(1e6);

        table.lookup(std::span<std::byte>(reinterpret_cast<std::byte*>(key.data()), key.size()), search_result.get());
        std::cout << search_result << std::endl;
    }

    {
        // Recovery also works with variable sized records
        Hashtable<std::span<const std::byte>, std::span<const std::byte>, PartitionType::Hash> table("/mnt/pmem0/vogel/tabletest", false);
        std::string key = "Das Lied von der Glocke";

        std::unique_ptr<uint8_t[]> search_result = std::make_unique<uint8_t[]>(1e6);

        std::cout << "Found variable sized records after recovery? " << table.lookup(std::span<std::byte>(reinterpret_cast<std::byte*>(key.data()), key.size()), search_result.get()) << std::endl;

    }


    return 0;
}
